language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - build-tools=27.0.3

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build connectedCheck --stacktrace
  - sonar-scanner



cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
