language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./licenses/* "$ANDROID_HOME/licenses/"

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build connectedCheck --stacktrace

cache:
    directories:
      - '$HOME/.gradle'
      - '.gradle'
