language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - build-tools=19.1.0

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./licenses/* "$ANDROID_HOME/licenses/"

before_script:
  - chmod +x gradlew

sscript:
  - ./gradlew clean build connectedCheck --stacktrace

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'
